server:
  port: ${PORT:8080}
logging:
  level:
    org:
      atmosphere: warn

spring:
  mustache:
    check-template-location: false

# Launch the default browser when starting the application in development mode
vaadin:
  launch-browser: true
# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/integrations/spring/configuration#special-configuration-parameters
  allowed-packages: com.vaadin,org.vaadin,com.example.application

football-api:
  base-url: https://api-football-v1.p.rapidapi.com/v3
  api-key: ${FOOTBALL_API_KEY}
  host: api-football-v1.p.rapidapi.com
